USE ujian_sekolah_kedinasan;

-- TWK Questions
INSERT INTO soal (kategori_id, pertanyaan, opsi_a, opsi_b, opsi_c, opsi_d, opsi_e, jawaban_benar, pembahasan, tips) VALUES
(1, 'Negara X adalah sebuah negara yang baru saja merdeka dan sedang berusaha membangun rasa nasionalisme di kalangan warganya. Proses ini dilakukan melalui implementasi berbagai program pemerintah dan penyebaran nilai-nilai patriotisme dalam pendidikan. Namun, beberapa tantangan tampaknya menjadi penghambat dalam upaya tersebut. Antara lain: Banyak warga Negara X yang memilih untuk bekerja di negara lain dan mengadopsi gaya hidup serta budaya negara tersebut. Sebagian masyarakat Negara X lebih tertarik pada barang-barang impor dibandingkan produk lokal. Penyiaran dan media di Negara X banyak didominasi oleh konten dari luar negeri. Konflik internal antara berbagai kelompok etnis dan agama yang berbeda. Pengetahuan dan apresiasi terhadap sejarah dan budaya lokal cukup tinggi di kalangan masyarakat berusia. Berdasarkan kasus di atas, mana faktor yang paling mungkin menjadi penghambat utama dalam membangun semangat nasionalisme di Negara X?', 'Globalisasi', 'Kesenjangan sosial', 'Pendidikan yang kurang efektif', 'Sumber daya manusia yang kurang', 'Kurangnya dukungan dari pemerintah', 'A', 'Globalisasi merupakan fenomena di mana dunia semakin terhubung dari segi teknologi, ekonomi, dan budaya. Dalam kasus Negara X, globalisasi memiliki pengaruh yang signifikan sebagai penghambat perkembangan nasionalisme. Hal ini dapat dilihat dari beberapa indikasi: 1) Migrasi tenaga kerja: Banyak warga Negara X yang memilih untuk bekerja di negara lain. Migrasi tenaga kerja ini cenderung membuat mereka mengadopsi gaya hidup serta budaya negara di mana mereka bekerja, yang dapat berpotensi mengurangi ikatan mereka dengan Negara X. 2) Dominasi barang dan layanan impor: Ketertarikan masyarakat Negara X terhadap barang-barang impor di atas produk lokal menunjukkan dampak globalisasi. 3) Dominasi konten media asing: Media memainkan peran penting dalam membentuk persepsi masyarakat. Melalui tiga indikasi ini, dapat disimpulkan bahwa globalisasi adalah faktor utama yang menghambat pembangunan semangat nasionalisme di Negara X.', 'Untuk soal TWK tentang nasionalisme, perhatikan konteks globalisasi dan dampaknya terhadap identitas nasional. Cari indikator-indikator yang menunjukkan pengaruh asing terhadap kehidupan lokal.'),

(1, 'Pada masa penjajahan, beberapa pemuda Indonesia seperti Ernest Douwes Dekker, Soewardi Soerjaningrat dan Tjipto Mangunkusumo mendirikan organisasi yang bernama Indische Party. Organisasi ini dikenal sebagai organisasi pertama yang mencetuskan konsep merdeka, yaitu bebas dari penjajahan Belanda dan menjadi fondasi penting dalam paham nasionalisme Indonesia. Peran Indische Party dan konsep merdeka memiliki pengaruh yang signifikan dalam sejarah kemerdekaan Indonesia. Bagaimanakah dampak konsep merdeka dan paham nasionalisme yang ditetapkan oleh Indische Party dalam perjuangan bangsa Indonesia hingga hari ini?', 'Menginspirasi pembuatan Pancasila sebagai dasar negara', 'Mendorong pertumbuhan partai-partai politik di Indonesia', 'Mendorong terbentuknya kesadaran kolektif untuk merdeka', 'Mendorong penggunaan Bahasa Indonesia sebagai bahasa resmi', 'Menstimulasi pembentukan lembaga-lembaga pemerintahan setelah kemerdekaan', 'C', 'Konsep merdeka dan paham nasionalisme yang disuarakan oleh Indische Party dapat dianggap sebagai gerakan awal yang signifikan dalam mendorong terbentuknya kesadaran kolektif untuk merdeka di Indonesia. Kesadaran kolektif ini merujuk pada pemahaman bersama di antara penduduk Indonesia bahwa mereka menginginkan dan berhak atas kemerdekaan negara mereka sendiri, bebas dari penjajahan asing. Paham nasionalisme ini meletakkan dasar bagi perjuangan Indonesia untuk mendapatkan kemerdekaan. Ide-ide dari Indische Party, termasuk konsep merdeka dan nasionalisme, membantu menguatkan perlawanan terhadap penjajah dan membentuk pergerakan nasionalis yang lebih besar yang akhirnya sukses memenangkan kemerdekaan Indonesia.', 'Untuk soal sejarah pergerakan nasional, pahami konsep dasar dari setiap organisasi dan dampaknya terhadap kesadaran kolektif bangsa.'),

(1, 'Pada 2021 silam, seorang aparat bernama Briptu Nikmal Idwan diduga melakukan pemerkosaan terhadap seorang remaja perempuan berusia 16 tahun di Mapolsek Jailolo Selatan, Halmahera Barat, Maluku Utara. Tindakan aparat ini jelas sekali bertentangan dengan....', 'UUD 1945 pasal 27 ayat 3', 'UUD 1945 pasal 30 ayat 3', 'UUD 1945 pasal 30 ayat 4', 'UU nomor 3 2002 pasal 9 ayat 1', 'UU nomor 3 2002 pasal 9 ayat 2', 'C', 'Bunyi masing-masing pasal: UUD 1945 pasal 27 ayat 3: Setiap warga negara berhak dan wajib ikut serta dalam pembelaan negara. UUD 1945 pasal 30 ayat 3: Tentara Nasional Indonesia terdiri atas Angkatan Darat, Angkatan Laut, dan Angkatan Udara sebagai alat negara yang bertugas mempertahankan, melindungi, dan memelihara keutuhan dan kedaulatan negara. UUD 1945 pasal 30 ayat 4: Kepolisian Negara Republik Indonesia sebagai alat negara yang menjaga keamanan dan ketertiban masyarakat bertugas melindungi, mengayomi, melayani masyarakat, serta menegakkan hukum. Tindakan pemerkosaan yang dilakukan oleh oknum aparat tersebut jelas melanggar UUD 1945 pasal 30 ayat 4. Polisi seharusnya melindungi dan mengayomi masyarakat, tetapi justru menjadi ancaman dan pelaku kriminal.', 'Untuk soal hukum/tata negara, hafalkan pasal-pasal penting dalam UUD 1945 terutama yang berkaitan dengan tugas dan fungsi lembaga negara.'),

(1, 'Nama Pandawara Group seringkali menjadi perbincangan dan trending topik di sosial media berkat aksi-aksi heroiknya dalam membersihkan sampah. Beranggotakan lima orang pemuda, yaitu Ikhsan Destian, Gliang Rahma, Muhammad Rifqi, Rafly Pasya, dan Agung Permana, tak jarang Pandawara Group mengajak masyarakat dan netizen untuk turut serta turun ke lapangan membersihkan sampah. Aksi kelompok pemuda ini mencerminkan salah satu nilai bela negara, yaitu....', 'cinta tanah air', 'kesadaran berbangsa dan bernegara', 'rela berkorban', 'memiliki kemampuan bela negara', 'memiliki kemampuan awal bela negara', 'A', 'Dalam kasus tersebut, Pandawara Group berupaya menjaga dan melestarikan lingkungan hidup. Aksi mereka ini sesuai dengan salah satu indikator cinta tanah air. Indikatornya adalah sebagai berikut: Mencintai, menjaga dan melestarikan Lingkungan Hidup, Menghargai dan menggunakan karya anak bangsa, Menggunakan produk dalam negeri, Menjaga dan memahami seluruh ruang wilayah NKRI, Menjaga nama baik bangsa dan negara, Mengenal wilayah tanah air tanpa rasa fanatisme kedaerahan.', 'Untuk soal bela negara, pahami indikator-indikator dari setiap nilai bela negara seperti cinta tanah air, kesadaran berbangsa, dan rela berkorban.'),

(1, 'Sikap di bawah ini yang berlandaskan nasionalisme yang berpengaruh pada kebijakan fiskal negara ialah....', 'Melakukan pembayaran pajak tepat pada waktu yang ditentukan', 'Melakukan suatu pekerjaan yang tidak bertentangan dengan hukum', 'Membeli produk-produk buatan dalam negeri', 'Menggunakan hak pilih pada pemilihan umum (pemilu)', 'Memiliki sikap toleransi tinggi terhadap orang/masyarakat yang berbeda keyakinan', 'A', 'Kebijakan fiskal adalah kebijakan yang dibuat oleh pemerintah untuk mengarahkan ekonomi suatu negara melalui pengeluaran (expenditure) dan pendapatan (income) dalam bentuk pajak oleh pemerintah. Jadi, membayar pajak tepat pada waktunya merupakan salah satu tindakan nasionalisme yang berpengaruh pada kebijakan fiskal negara.', 'Pahami definisi kebijakan fiskal (berkaitan dengan pajak dan pengeluaran negara) untuk membedakan dengan kebijakan moneter.');

-- TIU Questions
INSERT INTO soal (kategori_id, pertanyaan, opsi_a, opsi_b, opsi_c, opsi_d, opsi_e, jawaban_benar, pembahasan, tips) VALUES
(2, 'API : … = … : TERBASAHI', 'PANAS – CAIRAN', 'TERBAKAR – AIR', 'BERBAHAYA – GENANGAN', 'DIHINDARI – DIDEKATI', 'GAS – CAIR', 'B', 'Kata pertama kelompok kiri adalah API yang merupakan sebuah nomina atau kata benda, kata kedua di kelompok kanan adalah kata kerja. Berdasarkan hal tersebut, untuk mengisi bagian rumpang dibutuhkan kata benda dan kata kerja yang cocok sehingga TERBAKAR dan AIR dapat dipilih untuk melengkapi bagian rumpang. Hubungan: API menyebabkan terbakar, AIR mencegah terbakar/terbasahi.', 'Untuk soal analogi kata, identifikasi hubungan antar kata (sebab-akibat, sinonim, antonim, bagian-keseluruhan, dll) lalu cari pasangan dengan hubungan yang sama.'),

(2, 'KULKAS : SATU PINTU : DUA PINTU = …', 'APEL : SATU KERANJANG : DUA KERANJANG', 'ES KRIM : DINGIN : PANAS', 'RODA : BULAT : KOTAK', 'KASUR : RANJANG : ALAS TIDUR', 'MESIN CUCI : BUKAAN ATAS : BUKAAN DEPAN', 'E', 'Hubungan antara "KULKAS", "SATU PINTU", "DUA PINTU" adalah Kulkas memiliki jenis 1 pintu dan jenis 2 pintu. Hubungan ini sama seperti "MESIN CUCI", "BUKAAN ATAS", "BUKAAN DEPAN", mesin cuci memiliki jenis bukaan atas dan bukaan depan.', 'Untuk soal analogi tiga kata, identifikasi pola hubungan: objek memiliki variasi/jenis, lalu cari opsi dengan pola yang sama.'),

(2, 'Hubungan yang terdapat pada kalimat ikan adalah ekor sama seperti hubungan pada kalimat....', 'Manusia adalah kaki.', 'Kucing adalah buntut.', 'Daun adalah helai.', 'Bunga adalah buah.', 'Rumah adalah hunian.', 'C', 'Hubungan yang terdapat dalam kalimat ikan adalah ekor yang paling mungkin adalah ikan menggunakan penggolongan ekor dalam perhitungannya. Kalimat yang memiliki hubungan yang sama yaitu Daun adalah helai karena daun menggunakan penggolongan helai dalam perhitungannya. Ini adalah hubungan bagian-keseluruhan dengan satuan hitung.', 'Perhatikan hubungan semantik antar kata. Dalam soal ini, hubungan adalah objek-bagian dengan satuan penghitungan.'),

(2, 'Perhatikan pernyataan berikut! Setiap manusia di dunia pernah mengalami gigi rontok. Beberapa manusia di dunia adalah orang yang sangat tampan. Jadi,....', 'Beberapa manusia yang sangat tampan tidak pernah mengalami rontok gigi.', 'Beberapa manusia yang sangat tampan pernah mengalami rontok gigi.', 'Semua manusia yang sangat tampan tidak pernah mengalami rontok gigi.', 'Semua manusia yang sangat tampan pernah mengalami rontok gigi.', 'Semua manusia yang pernah mengalami rontok gigi adalah manusia yang sangat tampan.', 'B', 'Kesimpulan yang tepat berdasarkan kedua informasi adalah Beberapa manusia yang sangat tampan pernah mengalami rontok gigi. Kesimpulan ini ditarik berdasarkan pernyataan bahwa Setiap manusia di dunia pernah mengalami gigi rontok. Karena Beberapa manusia di dunia adalah orang yang sangat tampan, maka orang tersebut tetap pernah mengalami rontok gigi. Ini adalah silogisme dengan premis universal dan partikular.', 'Untuk soal silogisme, gunakan aturan logika: dari "semua A adalah B" dan "beberapa A adalah C" dapat disimpulkan "beberapa C adalah B".'),

(2, 'Orang-orang yang rajin membaca buku pasti memiliki pengetahuan yang luas. Orang yang memiliki pengetahuan luas sering kali lebih kreatif dalam memecahkan masalah. Hal ini membuat seseorang sukses dalam kariernya. Kesimpulan yang dapat ditarik dari premis-premis di atas adalah....', 'Orang yang sukses dalam kariernya pasti rajin membaca buku.', 'Orang yang rajin membaca buku sukses dalam kariernya.', 'Orang yang kreatif dalam memecahkan masalah pasti memiliki pengetahuan luas.', 'Orang yang sukses dalam karier pasti sering kali lebih kreatif dalam memecahkan masalah.', 'Orang yang sukses dalam karier sering kali rajin membaca buku.', 'B', 'Premis pertama menyatakan bahwa orang yang rajin membaca buku (p) memiliki pengetahuan luas (q). Premis kedua menyatakan bahwa orang yang memiliki pengetahuan luas (q) lebih kreatif dalam memecahkan masalah (r). Premis ketiga menyatakan bahwa Hal ini (orang yang kreatif dalam memecahkan masalah) (r) membuat seseorang sukses dalam kariernya (s). P1: p → q, P2: q → r, P3: r → s. Dari P1, P2 dan P3 dapat kita ambil kesimpulan sehingga berlaku p → s, kesimpulan ini memiliki bentuk kalimat Orang yang rajin membaca buku sukses dalam kariernya.', 'Untuk silogisme berantai, gabungkan semua premis: jika A→B, B→C, C→D, maka A→D.'),

(2, '65, 60, 45, 40, …, 20, 10, 5', '5', '25', '30', '35', '40', 'B', 'Bilangan deret terbentuk dengan pola angka dimana angka setelahnya (sepasang) memiliki selisih 5 atau -5. Pola: 65-60=5, 60-45=15, 45-40=5, 40-?=15, ?-20=5, 20-10=10, 10-5=5. Pola selisih: 5, 15, 5, 15, 5, 10, 5. Untuk ? = 25, maka 40-25=15 dan 25-20=5. Pola konsisten.', 'Untuk deret angka, cari pola selisih antar angka. Perhatikan apakah ada pola berulang atau naik-turun.'),

(2, 'Suap : Politik = ……….. : …………', 'Korupsi : nepotisme', 'Sontek : Ujian', 'Perampok : Polisi', 'Culas : Sifat', 'Joki : Ganti', 'B', 'Suap dilarang dalam Politik. Sontek dilarang dalam ujian. Hubungan: perbuatan negatif yang dilarang dalam konteks tertentu.', 'Identifikasi hubungan: X dilarang dalam Y. Cari pasangan dengan hubungan yang sama.'),

(2, 'Asia : Jepang : Sapporo = ….. : …… : ……..', 'Asia : Baghdah : Khalifah', 'Eropa : London : Coloseum', 'Amerika : Amerika Serikat : Liberty', 'Kelimutu : Flores : Indonesia', 'Benua : Pulau : Berpenduduk', 'C', 'Salah satu Negara yang ada di benua ASIA adalah Jepang yang memiliki ikon wisata Sapporo. Salah satu Negara yang ada di benua Amerika adalah Amerika Serikat yang memiliki ikon wisata Liberty. Hubungan: Benua : Negara di benua tersebut : Ikon/kota terkenal.', 'Untuk analogi tiga kata, identifikasi hierarki: Benua → Negara → Ikon/Kota.');

-- TKP Questions
INSERT INTO soal (kategori_id, pertanyaan, opsi_a, opsi_b, opsi_c, opsi_d, opsi_e, jawaban_benar, pembahasan, tips) VALUES
(3, 'Saat Anda menghadapi situasi sulit di tempat kerja, apa yang akan Anda lakukan?', 'Mengeluh dan mencari kesalahan orang lain', 'Menghindar dan menunda penyelesaian masalah', 'Menganalisis masalah dan mencari solusi dengan tenang', 'Meminta bantuan tanpa mencoba menyelesaikan sendiri', 'Menyerah dan mencari pekerjaan lain', 'C', 'Jawaban C menunjukkan sikap tanggung jawab, kemampuan problem solving, dan ketenangan dalam menghadapi masalah. Ini adalah karakteristik yang diinginkan untuk pegawai negeri/sekolah kedinasan.', 'Untuk soal TKP, pilih jawaban yang menunjukkan sikap positif, tanggung jawab, jujur, dan profesional.'),

(3, 'Rekan kerja Anda melakukan kesalahan yang tidak disengaja. Apa tindakan Anda?', 'Melaporkan ke atasan untuk mendapatkan keuntungan pribadi', 'Menertawakan dan mengumumkan kesalahan tersebut', 'Memberi tahu rekan tersebut dan menawarkan bantuan', 'Pura-pura tidak tahu dan membiarkan saja', 'Mencari-cari kesalahan lain dari rekan tersebut', 'C', 'Jawaban C menunjukkan sikap kepedulian, kerjasama, dan integritas. Memberi tahu dengan cara yang baik dan menawarkan bantuan adalah sikap yang profesional.', 'TKP mengukur karakteristik pribadi. Pilih jawaban yang menunjukkan sikap kolaboratif, empati, dan integritas tinggi.'),

(3, 'Anda mendapatkan tugas baru yang menantang. Sikap Anda adalah....', 'Menolak tugas tersebut karena terlalu sulit', 'Menerima tapi tidak serius mengerjakannya', 'Menerima dengan antusias dan belajar untuk menyelesaikannya', 'Menunda mengerjakan sampai deadline dekat', 'Minta orang lain mengerjakan untuk Anda', 'C', 'Jawaban C menunjukkan sikap antusias, motivasi belajar, dan tanggung jawab. Ini adalah karakteristik yang dicari untuk pegawai kedinasan.', 'Pilih jawaban yang menunjukkan motivasi, antusiasme, dan kemauan untuk belajar dan berkembang.'),

(3, 'Atasan memberikan kritik terhadap pekerjaan Anda. Reaksi Anda adalah....', 'Marah dan merasa tersinggung', 'Mengabaikan kritik dan tetap melakukan cara sendiri', 'Menerima kritik dengan terbuka dan memperbaiki diri', 'Mencari alasan untuk membela diri', 'Menggosipkan atasan di belakang', 'C', 'Jawaban C menunjukkan sikap terbuka terhadap masukan, kemauan untuk memperbaiki diri, dan kedewasaan emosional.', 'Untuk soal TKP tentang kritik/masukan, pilih jawaban yang menunjukkan keterbukaan, kedewasaan, dan kemauan untuk berkembang.'),

(3, 'Dalam situasi darurat, apa yang akan Anda lakukan?', 'Panik dan tidak bisa berpikir jernih', 'Menunggu instruksi dari orang lain tanpa inisiatif', 'Tetap tenang dan mengambil tindakan yang diperlukan', 'Lari dari situasi tersebut', 'Menyalahkan keadaan', 'C', 'Jawaban C menunjukkan kemampuan mengontrol emosi, ketenangan di bawah tekanan, dan kemampuan pengambilan keputusan.', 'Pilih jawaban yang menunjukkan ketenangan, kemampuan pengambilan keputusan, dan tanggung jawab dalam situasi darurat.');
