-- Complete Database Setup for Ujian Sekolah Kedinasan
-- This script combines all necessary tables and fixes inconsistencies

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

-- Database creation (if not exists)
CREATE DATABASE IF NOT EXISTS ujian_sekolah_kedinasan CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ujian_sekolah_kedinasan;

-- ============================================
-- CORE TABLES
-- ============================================

-- Users table (CRITICAL - was missing)
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    role ENUM('admin', 'user') DEFAULT 'user',
    api_key VARCHAR(64) UNIQUE,
    last_login TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert default admin user (password: admin123 - hashed)
INSERT INTO users (username, password, role, api_key) VALUES
('admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin', NULL)
ON DUPLICATE KEY UPDATE username=username;

-- Tabel kategori soal
CREATE TABLE IF NOT EXISTS kategori_soal (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama_kategori VARCHAR(50) NOT NULL,
    deskripsi TEXT,
    passing_grade INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert kategori soal
INSERT INTO kategori_soal (nama_kategori, deskripsi, passing_grade) VALUES
('TWK', 'Tes Wawasan Kebangsaan - Nasionalisme, Integritas, Bela Negara, Pilar Negara, Bahasa Indonesia', 65),
('TIU', 'Tes Intelegensi Umum - Verbal, Numerik, Figural', 80),
('TKP', 'Tes Karakteristik Pribadi', 166),
('TPA', 'Tes Potensi Akademik - Bahasa, Numerik, Logika', 70),
('PSIKOLOGIS', 'Tes Psikologis - Kepribadian, Motivasi', 166)
ON DUPLICATE KEY UPDATE nama_kategori=nama_kategori;

-- Tabel soal
CREATE TABLE IF NOT EXISTS soal (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kategori_id INT NOT NULL,
    pertanyaan TEXT NOT NULL,
    opsi_a TEXT NOT NULL,
    opsi_b TEXT NOT NULL,
    opsi_c TEXT NOT NULL,
    opsi_d TEXT NOT NULL,
    opsi_e TEXT NOT NULL,
    jawaban_benar CHAR(1) NOT NULL,
    pembahasan TEXT,
    tips TEXT,
    tingkat ENUM('mudah', 'sedang', 'sulit') DEFAULT 'sedang',
    irt_a DECIMAL(5,4) DEFAULT NULL COMMENT 'discrimination parameter',
    irt_b DECIMAL(5,4) DEFAULT NULL COMMENT 'difficulty parameter',
    irt_c DECIMAL(5,4) DEFAULT NULL COMMENT 'guessing parameter',
    discrimination_index DECIMAL(5,4) DEFAULT NULL COMMENT 'point-biserial correlation',
    item_quality ENUM('excellent', 'good', 'fair', 'poor') DEFAULT NULL,
    generated_by_ai TINYINT(1) DEFAULT 0 COMMENT 'whether question was generated by AI',
    ai_model VARCHAR(100) DEFAULT NULL COMMENT 'AI model used for generation',
    ai_generated_at TIMESTAMP NULL COMMENT 'when AI generated the question',
    quality_score DECIMAL(5,4) DEFAULT NULL COMMENT 'AI quality score (0-1)',
    review_status ENUM('pending', 'approved', 'rejected') DEFAULT NULL COMMENT 'human review status',
    reviewed_by INT DEFAULT NULL COMMENT 'admin who reviewed the question',
    reviewed_at TIMESTAMP NULL COMMENT 'when question was reviewed',
    bloom_level ENUM('remember', 'understand', 'apply', 'analyze', 'evaluate', 'create') DEFAULT NULL COMMENT 'Bloom taxonomy level',
    cognitive_load ENUM('low', 'medium', 'high') DEFAULT NULL COMMENT 'estimated cognitive load',
    avg_time_seconds INT DEFAULT NULL COMMENT 'average time to answer in seconds',
    learning_objective TEXT DEFAULT NULL COMMENT 'learning objective this question tests',
    expert_reviewed TINYINT(1) DEFAULT 0 COMMENT 'whether reviewed by subject matter expert',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (kategori_id) REFERENCES kategori_soal(id) ON DELETE CASCADE,
    INDEX idx_kategori (kategori_id),
    INDEX idx_tingkat (tingkat)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Tabel hasil ujian
CREATE TABLE IF NOT EXISTS hasil_ujian (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT DEFAULT NULL,
    nama_peserta VARCHAR(100) NOT NULL,
    tanggal_ujian DATETIME DEFAULT CURRENT_TIMESTAMP,
    durasi_menit INT NOT NULL,
    nilai_twk INT DEFAULT 0,
    nilai_tiu INT DEFAULT 0,
    nilai_tkp INT DEFAULT 0,
    nilai_tpa INT DEFAULT 0,
    nilai_psikologis INT DEFAULT 0,
    nilai_total INT DEFAULT 0,
    status_lulus VARCHAR(20) DEFAULT 'TIDAK LULUS',
    jawaban_peserta TEXT,
    verification_code VARCHAR(32) UNIQUE,
    INDEX idx_tanggal (tanggal_ujian),
    INDEX idx_status (status_lulus),
    INDEX idx_user (user_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Tabel sesi ujian (untuk tracking real-time)
CREATE TABLE IF NOT EXISTS sesi_ujian (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT DEFAULT NULL,
    nama_peserta VARCHAR(100) NOT NULL,
    waktu_mulai DATETIME DEFAULT CURRENT_TIMESTAMP,
    waktu_selesai DATETIME,
    durasi_menit INT NOT NULL,
    soal_teracak TEXT,
    jawaban_sementara TEXT,
    status ENUM('berjalan', 'selesai', 'timeout') DEFAULT 'berjalan',
    ability_estimate DECIMAL(10,4) DEFAULT 0 COMMENT 'estimated ability level',
    ability_history TEXT COMMENT 'JSON array of ability estimates during exam',
    confidence_level DECIMAL(5,4) DEFAULT 0 COMMENT 'confidence in ability estimate',
    cat_enabled TINYINT(1) DEFAULT 0 COMMENT 'whether CAT is enabled for this session',
    INDEX idx_status (status),
    INDEX idx_nama (nama_peserta),
    INDEX idx_user (user_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Tabel tips dan trik umum
CREATE TABLE IF NOT EXISTS tips_umum (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kategori VARCHAR(50),
    judul VARCHAR(200),
    konten TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert tips umum
INSERT INTO tips_umum (kategori, judul, konten) VALUES
('umum', 'Jangan Terburu-buru', 'Banyak faktor yang mengakibatkan diri kita seakan mengerjakan soal ujian secara cepat dan terburu-buru. Faktor waktu ujian yang tidak sebanding dengan jumlah soal ujian, hingga faktor teman-teman satu ruangan anda yang mungkin selesai secara cepat dan mengakibatkan anda menjadi tertekan untuk bisa menyelesaikannya secara cepat juga. Hal tersebut sebisa mungkin harus anda hindari.'),
('umum', 'Fokus dan Teliti', 'Pada dasarnya, ketika anda merasa tegang ketika menghadapi sesuatu, anda akan sangat sulit untuk berkonsentrasi terhadap keadaan sekitar anda. Perhatikan setiap soal dengan teliti, baik dari segi kosakata hingga tipe soalnya.'),
('umum', 'Kerjakan Soal yang Dapat Dijawab', 'Dalam mengerjakan soal Ujian SKD disarankan untuk mengerjakan soal secara berurutan dari nomor 1 hingga 100. Bila memang terpaksa tidak bisa menjawab soal, bisa melewati terlebih dahulu dan mengerjakan soal berikutnya.'),
('strategi', 'Urutan Pengerjaan Materi', 'Kerjakan terlebih dahulu soal TWK sampai selesai, kemudian loncat mengerjakan soal TKP sampai selesai. Bila kamu mengerjakan dua materi tersebut terlebih dahulu, perkiraan selesai dalam waktu 30-40 menit. Sisa waktu digunakan untuk mengerjakan soal materi TIU.'),
('tiu', 'Tips TIU - Hitung Cepat', 'Untuk soal hitungan cepat, gunakan teknik estimasi dan eliminasi. Jangan menghitung secara detail jika tidak perlu. Perkirakan jawaban yang paling masuk akal.'),
('twk', 'Tips TWK - Pahami Konsep', 'Untuk soal TWK, pahami konsep dasar nasionalisme, integritas, dan bela negara. Baca dengan teliti setiap pertanyaan karena seringkali ada jebakan dalam pemilihan kata.'),
('tkp', 'Tips TKP - Jujur pada Diri Sendiri', 'Soal TKP mengukur kepribadian Anda. Jawablah dengan jujur sesuai dengan karakter Anda. Jangan mencoba menebak jawaban yang dianggap "benar" karena sistem penilaian TKP berbeda dengan TWK dan TIU.'),
('tpa', 'Tips TPA - Latihan Rutin', 'TPA menguji potensi akademik Anda. Latihan soal secara rutin akan membantu meningkatkan kecepatan dan akurasi dalam mengerjakan soal bahasa, numerik, dan logika.'),
('psikologis', 'Tips Psikologis - Tenang dan Waspada', 'Tes psikologis mengukur kepribadian dan motivasi Anda. Tetaplah tenang dan wasapda saat mengerjakan. Jawablah sesuai dengan perasaan dan pemikiran Anda yang sebenarnya.'),
('tpa', 'Tips TPA - Manajemen Waktu', 'Bagi waktu secara proporsional untuk setiap jenis soal TPA. Jangan terjebak terlalu lama pada satu soal yang sulit. Lewati dan kembali lagi jika ada waktu sisa.'),
('psikologis', 'Tips Psikologis - Konsistensi', 'Jawablah soal psikologis dengan konsisten. Jangan berpindah sikap di tengah tes karena ini dapat mempengaruhi hasil penilaian kepribadian Anda.')
ON DUPLICATE KEY UPDATE judul=judul;

-- ============================================
-- PAKET TRYOUT
-- ============================================

-- Tabel Paket Tryout
CREATE TABLE IF NOT EXISTS paket_tryout (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama_paket VARCHAR(200) NOT NULL,
    deskripsi TEXT,
    durasi INT DEFAULT 100, -- dalam menit
    kategori_id INT,
    total_soal INT DEFAULT 30,
    is_active TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (kategori_id) REFERENCES kategori_soal(id)
);

-- Insert sample paket data
INSERT INTO paket_tryout (nama_paket, deskripsi, durasi, kategori_id, total_soal) VALUES
('Paket 1 - TWK', 'Tes Wawasan Kebangsaan - Paket 1', 100, 1, 30),
('Paket 2 - TIU', 'Tes Intelegensi Umum - Paket 1', 100, 2, 30),
('Paket 3 - TKP', 'Tes Karakteristik Pribadi - Paket 1', 100, 3, 30),
('Paket 4 - Full SKD', 'Full Seleksi Kompetensi Dasar', 100, NULL, 100),
('Paket 5 - Latihan Mudah', 'Paket latihan dengan tingkat kesulitan mudah', 100, NULL, 50)
ON DUPLICATE KEY UPDATE nama_paket=nama_paket;

-- ============================================
-- HIGH PRIORITY IMPROVEMENTS
-- ============================================

-- Sertifikat Digital
CREATE TABLE IF NOT EXISTS sertifikat (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT DEFAULT NULL,
    nama_peserta VARCHAR(100),
    hasil_id INT,
    verification_code VARCHAR(32) UNIQUE,
    qr_code TEXT,
    issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (hasil_id) REFERENCES hasil_ujian(id)
);

-- Leaderboard Opt-out
CREATE TABLE IF NOT EXISTS leaderboard_optout (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama_peserta VARCHAR(100) UNIQUE,
    opted_out_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Paket Blueprint
CREATE TABLE IF NOT EXISTS paket_blueprint (
    id INT AUTO_INCREMENT PRIMARY KEY,
    paket_id INT,
    kategori_id INT,
    target_count INT DEFAULT 0,
    min_difficulty ENUM('mudah', 'sedang', 'sulit') DEFAULT 'sedang',
    max_difficulty ENUM('mudah', 'sedang', 'sulit') DEFAULT 'sedang',
    FOREIGN KEY (paket_id) REFERENCES paket_tryout(id) ON DELETE CASCADE,
    FOREIGN KEY (kategori_id) REFERENCES kategori_soal(id)
);

-- ============================================
-- AI ANALYSIS
-- ============================================

-- Tabel untuk analisis kelemahan peserta per kategori
CREATE TABLE IF NOT EXISTS analisis_kelemahan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    sesi_id INT,
    kategori_id INT,
    total_soal INT DEFAULT 0,
    benar INT DEFAULT 0,
    salah INT DEFAULT 0,
    kosong INT DEFAULT 0,
    persen_benar DECIMAL(5,2) DEFAULT 0,
    tingkat_kelemahan ENUM('rendah', 'sedang', 'tinggi', 'sangat_tinggi') DEFAULT 'sedang',
    rekomendasi TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (sesi_id) REFERENCES sesi_ujian(id) ON DELETE CASCADE,
    FOREIGN KEY (kategori_id) REFERENCES kategori_soal(id)
);

-- Tabel untuk tips & tricks penyelesaian soal
CREATE TABLE IF NOT EXISTS tips_tricks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kategori_id INT,
    tipe_tips ENUM('umum', 'spesifik', 'strategi', 'shortcut') DEFAULT 'umum',
    judul VARCHAR(255),
    konten TEXT,
    contoh TEXT,
    prioritas INT DEFAULT 0,
    aktif TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (kategori_id) REFERENCES kategori_soal(id)
);

-- Insert sample tips & tricks
INSERT INTO tips_tricks (kategori_id, tipe_tips, judul, konten, contoh, prioritas) VALUES
(1, 'umum', 'Tips Menjawab TWK', 'Baca soal dengan teliti dan pahami konteks sejarah dan ideologi bangsa', 'Selalu kaitkan dengan Pancasila dan UUD 1945', 1),
(1, 'strategi', 'Strategi TWK', 'Fokus pada materi sejarah, geografi, dan ideologi negara', 'Pelajari pahlawan nasional dan peristiwa penting', 2),
(2, 'umum', 'Tips Menjawab TIU', 'Gunakan logika matematika dan pola untuk mempercepat penyelesaian', 'Gunakan teknik eliminasi untuk opsi yang jelas salah', 1),
(2, 'shortcut', 'Shortcut TIU', 'Untuk soal deret, cari pola selisih antar angka', 'Contoh: 2,4,6,8 selisihnya 2, angka berikutnya 10', 3),
(3, 'umum', 'Tips Menjawab TKP', 'Jawab sesuai kepribadian dan karakter Anda yang sebenarnya', 'Jangan pura-pura, sistem akan mendeteksi ketidakkonsistenan', 1),
(3, 'strategi', 'Strategi TKP', 'Pahami skala penilaian (1-5) dan konteks situasi kerja', 'Nilai 5 = Sangat Sesuai, Nilai 1 = Sangat Tidak Sesuai', 2)
ON DUPLICATE KEY UPDATE judul=judul;

-- Tabel untuk relasi tips dengan soal (untuk tips spesifik)
CREATE TABLE IF NOT EXISTS tips_soal (
    tips_id INT,
    soal_id INT,
    PRIMARY KEY (tips_id, soal_id),
    FOREIGN KEY (tips_id) REFERENCES tips_tricks(id) ON DELETE CASCADE,
    FOREIGN KEY (soal_id) REFERENCES soal(id) ON DELETE CASCADE
);

-- ============================================
-- BAHAN PELAJARAN
-- ============================================

-- Tabel untuk bahan pelajaran
CREATE TABLE IF NOT EXISTS bahan_pelajaran (
    id INT AUTO_INCREMENT PRIMARY KEY,
    soal_id INT NOT NULL,
    judul VARCHAR(255),
    konten LONGTEXT,
    tipe ENUM('teks', 'video', 'pdf', 'link') DEFAULT 'teks',
    url VARCHAR(500),
    file_path VARCHAR(255),
    urutan INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (soal_id) REFERENCES soal(id) ON DELETE CASCADE
);

-- Tabel untuk rekomendasi belajar peserta
CREATE TABLE IF NOT EXISTS rekomendasi_belajar (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    sesi_id INT,
    soal_id INT,
    alasan ENUM('salah', 'ragu', 'review') NOT NULL,
    status ENUM('pending', 'dipelajari', 'dikuasai') DEFAULT 'pending',
    dipelajari_pada TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (soal_id) REFERENCES soal(id) ON DELETE CASCADE
);

-- Tabel untuk topik pelajaran (untuk grouping)
CREATE TABLE IF NOT EXISTS topik_pelajaran (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kategori_id INT,
    nama_topik VARCHAR(200),
    deskripsi TEXT,
    urutan INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (kategori_id) REFERENCES kategori_soal(id)
);

-- Insert sample topik
INSERT INTO topik_pelajaran (kategori_id, nama_topik, deskripsi, urutan) VALUES
(1, 'Ideologi Pancasila', 'Materi tentang ideologi dan dasar negara', 1),
(1, 'Sejarah Indonesia', 'Sejarah perjuangan dan kemerdekaan Indonesia', 2),
(1, 'Geografi Indonesia', 'Geografi dan wilayah Indonesia', 3),
(2, 'Logika Matematika', 'Pemecahan masalah logis dan matematika', 1),
(2, 'Verbal Reasoning', 'Penalaran verbal dan bahasa', 2),
(2, 'Spasial Reasoning', 'Penalaran spasial dan visual', 3),
(3, 'Kepribadian', 'Asesmen kepribadian dan karakter', 1),
(3, 'Etika Kerja', 'Etika dan profesionalisme kerja', 2)
ON DUPLICATE KEY UPDATE nama_topik=nama_topik;

-- Relasi soal ke topik
CREATE TABLE IF NOT EXISTS soal_topik (
    soal_id INT,
    topik_id INT,
    PRIMARY KEY (soal_id, topik_id),
    FOREIGN KEY (soal_id) REFERENCES soal(id) ON DELETE CASCADE,
    FOREIGN KEY (topik_id) REFERENCES topik_pelajaran(id) ON DELETE CASCADE
);

-- ============================================
-- SOAL FREQUENCY
-- ============================================

-- Tabel untuk tracking frekuensi kemunculan soal
CREATE TABLE IF NOT EXISTS soal_frequency (
    id INT AUTO_INCREMENT PRIMARY KEY,
    soal_id INT NOT NULL,
    muncul_count INT DEFAULT 0,
    benar_count INT DEFAULT 0,
    salah_count INT DEFAULT 0,
    irt_a DECIMAL(5,4) DEFAULT NULL,
    irt_b DECIMAL(5,4) DEFAULT NULL,
    irt_c DECIMAL(5,4) DEFAULT NULL,
    discrimination_index DECIMAL(5,4) DEFAULT NULL,
    last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (soal_id) REFERENCES soal(id) ON DELETE CASCADE,
    UNIQUE KEY (soal_id)
);

-- Trigger untuk otomatis menambah record jika belum ada
DELIMITER //
DROP TRIGGER IF EXISTS ensure_soal_frequency//
CREATE TRIGGER ensure_soal_frequency
AFTER INSERT ON soal
FOR EACH ROW
BEGIN
    INSERT IGNORE INTO soal_frequency (soal_id, muncul_count) VALUES (NEW.id, 0);
END//
DELIMITER ;

-- ============================================
-- VIEWS
-- ============================================

-- View untuk analisis kelemahan lengkap
CREATE OR REPLACE VIEW v_analisis_kelemahan_lengkap AS
SELECT 
    ak.id,
    ak.user_id,
    ak.sesi_id,
    ak.kategori_id,
    k.nama_kategori,
    ak.total_soal,
    ak.benar,
    ak.salah,
    ak.kosong,
    ak.persen_benar,
    ak.tingkat_kelemahan,
    ak.rekomendasi,
    ak.created_at
FROM analisis_kelemahan ak
JOIN kategori_soal k ON ak.kategori_id = k.id
ORDER BY ak.persen_benar ASC;

-- View untuk bahan pelajaran lengkap dengan info soal
CREATE OR REPLACE VIEW v_bahan_pelajaran_lengkap AS
SELECT 
    bp.id,
    bp.soal_id,
    s.pertanyaan,
    s.kategori_id,
    k.nama_kategori,
    bp.judul,
    bp.konten,
    bp.tipe,
    bp.url,
    bp.file_path,
    bp.urutan,
    s.jawaban_benar,
    s.pembahasan
FROM bahan_pelajaran bp
JOIN soal s ON bp.soal_id = s.id
JOIN kategori_soal k ON s.kategori_id = k.id;

-- View untuk rekomendasi belajar peserta
CREATE OR REPLACE VIEW v_rekomendasi_belajar AS
SELECT 
    rb.id,
    rb.user_id,
    rb.sesi_id,
    rb.soal_id,
    s.pertanyaan,
    s.kategori_id,
    k.nama_kategori,
    rb.alasan,
    rb.status,
    rb.dipelajari_pada,
    rb.created_at,
    s.jawaban_benar,
    s.pembahasan
FROM rekomendasi_belajar rb
JOIN soal s ON rb.soal_id = s.id
JOIN kategori_soal k ON s.kategori_id = k.id;

-- View untuk statistik frekuensi soal
CREATE OR REPLACE VIEW v_soal_statistics AS
SELECT 
    s.id,
    s.pertanyaan,
    s.kategori_id,
    k.nama_kategori,
    COALESCE(sf.muncul_count, 0) as muncul_count,
    COALESCE(sf.benar_count, 0) as benar_count,
    COALESCE(sf.salah_count, 0) as salah_count,
    CASE 
        WHEN COALESCE(sf.muncul_count, 0) > 0 
        THEN ROUND((COALESCE(sf.benar_count, 0) / COALESCE(sf.muncul_count, 0)) * 100, 2)
        ELSE 0 
    END as persen_benar,
    CASE 
        WHEN COALESCE(sf.muncul_count, 0) > 0 
        THEN ROUND((COALESCE(sf.salah_count, 0) / COALESCE(sf.muncul_count, 0)) * 100, 2)
        ELSE 0 
    END as persen_salah
FROM soal s
LEFT JOIN kategori_soal k ON s.kategori_id = k.id
LEFT JOIN soal_frequency sf ON s.id = sf.soal_id;

COMMIT;
