-- LOW Priority Improvements Database Schema

-- 1. Adaptive Difficulty CAT
-- Add ability estimation tracking
ALTER TABLE sesi_ujian ADD COLUMN ability_estimate DECIMAL(10,4) DEFAULT 0 COMMENT 'estimated ability level';
ALTER TABLE sesi_ujian ADD COLUMN ability_history TEXT COMMENT 'JSON array of ability estimates during exam';
ALTER TABLE sesi_ujian ADD COLUMN confidence_level DECIMAL(5,4) DEFAULT 0 COMMENT 'confidence in ability estimate';
ALTER TABLE sesi_ujian ADD COLUMN cat_enabled TINYINT(1) DEFAULT 0 COMMENT 'whether CAT is enabled for this session';

-- 2. AI Generator Advanced
-- Add question generation tracking
ALTER TABLE soal ADD COLUMN generated_by_ai TINYINT(1) DEFAULT 0 COMMENT 'whether question was generated by AI';
ALTER TABLE soal ADD COLUMN ai_model VARCHAR(100) DEFAULT NULL COMMENT 'AI model used for generation';
ALTER TABLE soal ADD COLUMN ai_generated_at TIMESTAMP NULL COMMENT 'when AI generated the question';
ALTER TABLE soal ADD COLUMN quality_score DECIMAL(5,4) DEFAULT NULL COMMENT 'AI quality score (0-1)';
ALTER TABLE soal ADD COLUMN review_status ENUM('pending', 'approved', 'rejected') DEFAULT NULL COMMENT 'human review status';
ALTER TABLE soal ADD COLUMN reviewed_by INT DEFAULT NULL COMMENT 'admin who reviewed the question';
ALTER TABLE soal ADD COLUMN reviewed_at TIMESTAMP NULL COMMENT 'when question was reviewed';

-- 3. Tingkat Kesulitan Advanced
-- Add Bloom's taxonomy mapping
ALTER TABLE soal ADD COLUMN bloom_level ENUM('remember', 'understand', 'apply', 'analyze', 'evaluate', 'create') DEFAULT NULL COMMENT 'Bloom taxonomy level';
ALTER TABLE soal ADD COLUMN cognitive_load ENUM('low', 'medium', 'high') DEFAULT NULL COMMENT 'estimated cognitive load';
ALTER TABLE soal ADD COLUMN avg_time_seconds INT DEFAULT NULL COMMENT 'average time to answer in seconds';
ALTER TABLE soal ADD COLUMN learning_objective TEXT DEFAULT NULL COMMENT 'learning objective this question tests';
ALTER TABLE soal ADD COLUMN expert_reviewed TINYINT(1) DEFAULT 0 COMMENT 'whether reviewed by subject matter expert';
